#if defined _smlib_included
	#endinput
#endif
#define _smlib_included

#define SMLIB_VERSION "0.9.7"

#include "aio/smlib/general"

#include "aio/smlib/arrays"
#include "aio/smlib/clients"
#include "aio/smlib/colors"
#include "aio/smlib/concommands"
#include "aio/smlib/convars"
#include "aio/smlib/crypt"
#include "aio/smlib/debug"
#include "aio/smlib/dynarrays"
#include "aio/smlib/edicts"
#include "aio/smlib/effects"
#include "aio/smlib/entities"
#include "aio/smlib/files"
#include "aio/smlib/game"
#include "aio/smlib/math"
#include "aio/smlib/server"
#include "aio/smlib/strings"
#include "aio/smlib/sql"
#include "aio/smlib/teams"
#include "aio/smlib/vehicles"
#include "aio/smlib/weapons"
#include "aio/smlib/world"
