/*        <AIO MOD> (c) by <De Battista Clint - (http://doyou.watch)         */
/*                                                                           */
/*                       <AIO MOD> is licensed under a                       */
/* Creative Commons Attribution-NonCommercial-NoDerivs 4.0 Unported License. */
/*																			 */
/*      You should have received a copy of the license along with this       */
/*  work.  If not, see <http://creativecommons.org/licenses/by-nc-nd/4.0/>.  */
//***************************************************************************//
//***************************************************************************//
//*******************************AIO MOD ENUMS*******************************//
//***************************************************************************//
//***************************************************************************//

//***********************************//
//***********ENUMERATION*************//
//***********************************//

//Team group
enum Teams
{
	TeamNone = 0,
	TeamSpectator,
	TeamT,
	TeamCT
};

//Equipments slots
enum Slots
{
	SlotPrimary,
	SlotSecondary,
	SlotKnife,
	SlotGrenade,
	SlotC4,
	SlotSmoke,
	SlotFlash,
	SlotMolotov,
	SlotDecoy,
	SlotDefuse,
	SlotArmor,
	SlotNone
};